### ISSUE TITLE
Foutmeldingen

### ISSUE THREAD

**Issue by ajvdmeij** [ralphcrutzen/RGBDigit#1]
Hi Ralph,

Deze foutmeldingen krijg ik:

Arduino: 1.6.5 (Mac OS X), Board:"Arduino Micro"

In file included from /Users/arjan/Documents/Arduino/libraries/Time/DateStrings.cpp:10:0:
/Users/arjan/Documents/Arduino/libraries/Time/DateStrings.cpp:18:18: error: variable 'monthStr1' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
 char monthStr1[] PROGMEM = "January";
                  ^
/Users/arjan/Documents/Arduino/libraries/Time/DateStrings.cpp:19:18: error: variable 'monthStr2' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
 char monthStr2[] PROGMEM = "February";
                  ^
/Users/arjan/Documents/Arduino/libraries/Time/DateStrings.cpp:20:18: error: variable 'monthStr3' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
 char monthStr3[] PROGMEM = "March";
                  ^
/Users/arjan/Documents/Arduino/libraries/Time/DateStrings.cpp:21:18: error: variable 'monthStr4' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
 char monthStr4[] PROGMEM = "April";
                  ^
/Users/arjan/Documents/Arduino/libraries/Time/DateStrings.cpp:22:18: error: variable 'monthStr5' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
 char monthStr5[] PROGMEM = "May";
                  ^
/Users/arjan/Documents/Arduino/libraries/Time/DateStrings.cpp:23:18: error: variable 'monthStr6' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
 char monthStr6[] PROGMEM = "June";
                  ^
/Users/arjan/Documents/Arduino/libraries/Time/DateStrings.cpp:24:18: error: variable 'monthStr7' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
 char monthStr7[] PROGMEM = "July";
                  ^
/Users/arjan/Documents/Arduino/libraries/Time/DateStrings.cpp:25:18: error: variable 'monthStr8' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
 char monthStr8[] PROGMEM = "August";
                  ^
/Users/arjan/Documents/Arduino/libraries/Time/DateStrings.cpp:26:18: error: variable 'monthStr9' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
 char monthStr9[] PROGMEM = "September";
                  ^
/Users/arjan/Documents/Arduino/libraries/Time/DateStrings.cpp:27:19: error: variable 'monthStr10' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
 char monthStr10[] PROGMEM = "October";
                   ^
/Users/arjan/Documents/Arduino/libraries/Time/DateStrings.cpp:28:19: error: variable 'monthStr11' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
 char monthStr11[] PROGMEM = "November";
                   ^
/Users/arjan/Documents/Arduino/libraries/Time/DateStrings.cpp:29:19: error: variable 'monthStr12' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
 char monthStr12[] PROGMEM = "December";
                   ^
/Users/arjan/Documents/Arduino/libraries/Time/DateStrings.cpp:31:22: error: variable 'monthNames_P' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
 PGM_P monthNames_P[] PROGMEM = 
                      ^
/Users/arjan/Documents/Arduino/libraries/Time/DateStrings.cpp:37:26: error: variable 'monthShortNames_P' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
 char monthShortNames_P[] PROGMEM = "ErrJanFebMarAprMayJunJulAugSepOctNovDec";
                          ^
/Users/arjan/Documents/Arduino/libraries/Time/DateStrings.cpp:39:16: error: variable 'dayStr0' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
 char dayStr0[] PROGMEM = "Err";
                ^
/Users/arjan/Documents/Arduino/libraries/Time/DateStrings.cpp:40:16: error: variable 'dayStr1' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
 char dayStr1[] PROGMEM = "Sunday";
                ^
/Users/arjan/Documents/Arduino/libraries/Time/DateStrings.cpp:41:16: error: variable 'dayStr2' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
 char dayStr2[] PROGMEM = "Monday";
                ^
/Users/arjan/Documents/Arduino/libraries/Time/DateStrings.cpp:42:16: error: variable 'dayStr3' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
 char dayStr3[] PROGMEM = "Tuesday";
                ^
/Users/arjan/Documents/Arduino/libraries/Time/DateStrings.cpp:43:16: error: variable 'dayStr4' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
 char dayStr4[] PROGMEM = "Wednesday";
                ^
/Users/arjan/Documents/Arduino/libraries/Time/DateStrings.cpp:44:16: error: variable 'dayStr5' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
 char dayStr5[] PROGMEM = "Thursday";
                ^
/Users/arjan/Documents/Arduino/libraries/Time/DateStrings.cpp:45:16: error: variable 'dayStr6' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
 char dayStr6[] PROGMEM = "Friday";
                ^
/Users/arjan/Documents/Arduino/libraries/Time/DateStrings.cpp:46:16: error: variable 'dayStr7' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
 char dayStr7[] PROGMEM = "Saturday";
                ^
/Users/arjan/Documents/Arduino/libraries/Time/DateStrings.cpp:48:20: error: variable 'dayNames_P' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
 PGM_P dayNames_P[] PROGMEM = { dayStr0,dayStr1,dayStr2,dayStr3,dayStr4,dayStr5,dayStr6,dayStr7};
                    ^
/Users/arjan/Documents/Arduino/libraries/Time/DateStrings.cpp:49:24: error: variable 'dayShortNames_P' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
 char dayShortNames_P[] PROGMEM = "ErrSunMonTueWedThrFriSat";
                        ^
Multiple libraries were found for "IRremote.h"
 Used: /Users/arjan/Documents/Arduino/libraries/IRremote
 Not used: /Applications/Arduino.app/Contents/Java/libraries/RobotIRremote
Fout bij compileren.

  Dit rapport zou meer informatie hebben met
  "Tijdens de compilatie uitgebreide uitvoer weergeven"
  ingeschakeld in Bestand > Voorkeuren.

**Comment by ralphcrutzen** [comment]
Using the latest version of the Time libraray (https://github.com/PaulStoffregen/Time) will probably fix your problem.
