### ISSUE TITLE
Library covers too much other functionality

### ISSUE THREAD

**Issue by msurguy** [ralphcrutzen/RGBDigit#2]
Hello! 

Thanks for this code.

This library seems to be doing other functions that should be taken out of the library's domain.

Reading infrared codes, working with time and date,  reading temperature are not really important for the purpose of the RGB Digit library and could be taken out to be a separate library (or use existing Arduino libraries). 

I propose taking the functions that are not directly related to driving the 7 segment display out.

**Comment by ralphcrutzen** [comment]
I agree, although my RGB digit shield has an RTC and a temperature sensor.

**Comment by samscam** [comment]
Having just picked up some RGBDigits, I'm with @msurguy on this one. It should just control the 7 segment displays and not do anything else. Pull out anything else into other libraries if necessary.

**Comment by salvagione** [comment]
+1, 
I would also like to see a library just for the RBGDigit.
